#!/usr/bin/env python3
"""
从 PC 源码重新生成 src/sxfnames.h

为什么要重生成：
  原 sxfnames.h 的 g_sfx_fixed 是「把 Terraria.ID.SoundID 的字段按声明顺序
  编成 0..578 的稠密 id」当 type 用。但 PlaySound 的 type 只会是 SoundID 的
  70 个 const（0..69）之一，加上 style 才是变体 —— 那 509 条稠密 id Hook
  永远收不到，等于「按变体名命名的文件永远匹配不上」。

本生成器产出三张表：
  1. g_sfx_fixed  : 70 个 const           name -> type
  2. g_sfx_named  : 506 个 LegacySoundStyle 字段（含 variations 展开）
                                             name -> (type, style)
  3. g_sfx_style  : 音频家族资源名前缀     prefix -> type（配合 style 数字）
  查找时把输入与表名统一「小写 + 去掉下划线/空格」再比较，
  因此 NPC_Hit_26 / npc_hit_26 / NPCHit26 三种写法都能命中。

用法: gen_sxfnames.py <SoundID.cs> <LegacySoundPlayer.cs> <out.h>
"""
import re
import sys


def parse_soundid(path):
    src = open(path, encoding='utf-8', errors='ignore').read()
    consts = [(n, int(v)) for n, v in re.findall(r'public const int (\w+) = (\d+);', src)]
    fields = []          # (name, type, style)  已展开 variations
    track_idx = 0
    for m in re.finditer(r'public static readonly LegacySoundStyle (\w+) = ([^;]+);', src):
        name, expr = m.group(1), m.group(2)
        expr = re.sub(r'\.With\w+\([^)]*\)', '', expr)
        ct = re.search(r'CreateTrackable\(\s*"([^"]+)"\s*(?:,\s*(\d+))?', expr)
        if ct:
            vari = int(ct.group(2)) if ct.group(2) else 1
            base = track_idx
            track_idx += vari
            for k in range(vari):
                fields.append((name, 42, base + k))
            continue
        nl = re.search(r'new LegacySoundStyle\(\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*(\d+))?', expr)
        if nl:
            t = int(nl.group(1))
            s = int(nl.group(2))
            vari = int(nl.group(3)) if nl.group(3) else 1
            for k in range(vari):
                fields.append((name, t, s + k))
            continue
        # 引用别的字段（如 = SoundID.Item1.WithVolume(...)）
        ref = re.search(r'(?:SoundID\.)?(\w+)', expr)
        if ref:
            fields.append((ref.group(1), -1, -1))   # 稍后解析别名
    return consts, fields


# 家族资源名前缀 -> SoundID const 名（对应 LegacySoundPlayer.LoadAll 的数组）
FAMILIES = [
    ("dig_", "Dig"),
    ("player_hit_", "PlayerHit"),
    ("item_", "Item"),
    ("npc_hit_", "NPCHit"),
    ("npc_killed_", "NPCKilled"),
    ("female_hit_", "FemaleHit"),
    ("zombie_", "Zombie"),
    ("splash_", "Splash"),
    ("drip_", "Drip"),
    ("thunder_", "Thunder"),
    ("roar_", "Roar"),
    ("tink_", "Tink"),
    ("mech_", "Mech"),
    ("coin_", "CoinPickup"),
    ("coins", "Coins"),
    ("liquid_", None),   # 无对应 const，PlaySound 里归入 46
    ("custom/", None),   # trackable，由 g_sfx_named 覆盖
]

# 需要额外补的别名（前缀表表达不了的）
EXTRA = [
    ("research0", 64, -1),   # PC: case 64 用 SoundResearch[0]
    ("research1", 63, -1),
    ("research2", 63, -1),
    ("research3", 63, -1),
]


def parse_families(consts):
    cmap = {n: v for n, v in consts}
    out = []
    for pre, key in FAMILIES:
        if key is None:
            t = 46 if pre.startswith("liquid") else 42
        else:
            t = cmap.get(key)
        if t is None:
            continue
        out.append((pre, t))
    return out


def norm(s):
    return re.sub(r'[^a-z0-9]', '', s.lower())


def main():
    sid, lsp, out = sys.argv[1], sys.argv[2], sys.argv[3]
    consts, fields = parse_soundid(sid)
    if not consts:
        print('warning: no const int found; 表结构可能不对', file=sys.stderr)
    cmap = {n: v for n, v in consts}

    # 解析别名（type=-1 的条目指向别的字段），多轮迭代直到收敛
    resolved = [(n, t, s) for n, t, s in fields if t >= 0]
    pending = [(n, t, s) for n, t, s in fields if t < 0]
    for _ in range(4):
        if not pending:
            break
        known = {}
        for n, t, s in resolved:
            known.setdefault(n, (t, s))
        still = []
        for n, t, s in pending:
            t2, s2 = known.get(n, (-1, -1))
            if t2 >= 0:
                resolved.append((n, t2, s2))
            else:
                still.append((n, t, s))
        pending = still
    if pending:
        print('warning: 未能解析:', [p[0] for p in pending], file=sys.stderr)
    # 去重（同名多条目只留第一条）
    seen = set()
    uniq = []
    for n, t, s in resolved:
        k = (norm(n), t, s)
        if k in seen:
            continue
        seen.add(k)
        uniq.append((n, t, s))

    fams = parse_families(consts)
    uniq += EXTRA

    with open(out, 'w', encoding='utf-8') as f:
        f.write('/* auto-generated by tools/gen_sxfnames.py —— 请勿手改 */\n')
        f.write('#ifndef SXFN_NAMES_H\n#define SXFN_NAMES_H\n\n')
        f.write('#include <string.h>\n\n')

        f.write('typedef struct { const char* name; int type; } sfx_fixed_t;\n')
        f.write(f'/* SoundID 的 {len(consts)} 个 const：PlaySound 顶层 type */\n')
        f.write('static const sfx_fixed_t g_sfx_fixed[] = {\n')
        for n, v in consts:
            f.write('    {"%s",%d},\n' % (norm(n), v))
        f.write('};\n\n')

        f.write('typedef struct { const char* name; int type; int style; } sfx_named_t;\n')
        f.write(f'/* LegacySoundStyle 字段（expansion 展开后 {len(uniq)} 条）：name -> (SoundId, Style) */\n')
        f.write('static const sfx_named_t g_sfx_named[] = {\n')
        for n, t, s in uniq:
            f.write('    {"%s",%d,%d},\n' % (norm(n), t, s))
        f.write('};\n\n')

        f.write('typedef struct { const char* prefix; int type; } sfx_style_t;\n')
        f.write('/* 按资源名前缀的家族（如 NPC_Hit_26） */\n')
        f.write('static const sfx_style_t g_sfx_style[] = {\n')
        for p, t in fams:
            f.write('    {"%s",%d},\n' % (norm(p), t))
        f.write('};\n\n')

        f.write(r'''/* 归一化: 小写 + 去掉非字母数字 */
static void sfx_norm(const char* in, char* out, int cap){
    int i=0;
    for(const char* p=in; *p && i<cap-1; p++){
        char c=*p;
        if(c>='A'&&c<='Z') c+=32;
        if((c>='a'&&c<='z')||(c>='0'&&c<='9')) out[i++]=c;
    }
    out[i]=0;
}

/* base：文件名（可带扩展名）。命中返回 1；style=-1 表示只按 type 匹配。 */
static int sfx_name_lookup_ex(const char* base, int* type, int* style){
    char buf[160];
    sfx_norm(base, buf, sizeof(buf));
    *type=-1; *style=-1;
    if(!buf[0]) return 0;

    /* 1) 变体字段（精确）：name -> (type, style) */
    for(unsigned k=0;k<sizeof(g_sfx_named)/sizeof(g_sfx_named[0]);k++){
        if(strcmp(buf, g_sfx_named[k].name)==0){
            *type=g_sfx_named[k].type; *style=g_sfx_named[k].style; return 1;
        }
    }
    /* 2) const：name -> type */
    for(unsigned k=0;k<sizeof(g_sfx_fixed)/sizeof(g_sfx_fixed[0]);k++){
        if(strcmp(buf, g_sfx_fixed[k].name)==0){ *type=g_sfx_fixed[k].type; return 1; }
    }
    /* 3) 家族前缀 + 尾随数字：NPC_Hit_26 -> (3,26) */
    for(unsigned k=0;k<sizeof(g_sfx_style)/sizeof(g_sfx_style[0]);k++){
        const char* pre=g_sfx_style[k].prefix;
        size_t pl=strlen(pre);
        if(pl && strncmp(buf,pre,pl)==0){
            const char* q=buf+pl;
            if(*q<'0'||*q>'9') continue;
            int v=0; while(*q>='0'&&*q<='9'){ v=v*10+(*q-'0'); q++; }
            if(*q) continue;
            *type=g_sfx_style[k].type; *style=v; return 1;
        }
    }
    return 0;
}
static int sfx_name_lookup(const char* base, int* type, int* style){ return sfx_name_lookup_ex(base,type,style); }
#endif
''')
    print(f"consts={len(consts)} named={len(uniq)} families={len(fams)}")


if __name__ == '__main__':
    main()
